### PR TITLE
fix: Avoid processing directories with .java extension as files

### LINKED ISSUE #204: Directories ending in ".java" cause Sorald to crash
It thinks it's a viable java file.

### PR DESCRIPTION
**Pull request by slarse**
Fix #204 

This fixes a crash that occurs when you apply Sorald to a project that has a directory ending in `.java`.

This also applies to the miner, but I'll fix that separately.

### CODE REVIEW

File: src/main/java/sorald/processor/SoraldAbstractProcessor.java [hunk 1]
```diff
@@ -39,10 +39,10 @@ public SoraldAbstractProcessor initResource(String originalFilesPath, File baseD
             if (file.isFile()) {
                 filesToScan.add(file.getAbsolutePath());
             } else {
-                try (Stream<Path> walk = Files.walk(Paths.get(file.getAbsolutePath()))) {
+                try {
                     filesToScan =
-                            walk.map(x -> x.toFile().getAbsolutePath())
-                                    .filter(f -> f.endsWith(Constants.JAVA_EXT))
```
Comment (slarse) [inline src/main/java/sorald/processor/SoraldAbstractProcessor.java:45]: This is what caused the crash; it doesn't check if the file is actually a regular file (so it could be a directory ending with `.java`).

File: src/main/java/sorald/FileUtils.java [hunk 2]
```diff
@@ -52,4 +57,34 @@ public static boolean deleteDirectory(File directoryToBeDeleted) {
...
+     * @param ext A file extension including the leading dot
+     * @return All files in the given directory or any subdirectory with a matching extension
+     */
+    public static List<File> findFilesByExtension(File directory, String ext) throws IOException {
+        if (!directory.isDirectory()) {
+            throw new IllegalArgumentException(directory.toString() + " is not a directory");
+        }
+        try (Stream<Path> files = Files.walk(directory.toPath())) {
+            return files.map(Path::toFile)
+                    .filter(File::isFile)
```
Comment (slarse) [inline src/main/java/sorald/FileUtils.java:75]: This is the key :)
